admin_ui/package-lock.json
admin_ui/package.json
admin_ui/src/components/CSVButton.vue
admin_ui/src/main.ts
admin_ui/src/views/RowListing.vue

@dantownsend this is my try on exporting to csv. Probably it be slow for large and complex tables due to passing total number of rows to PiccoloCRUD __page_size param , but it's just idea.

adding export to csv

---

admin_ui/src/App.vue
admin_ui/src/components/BulkDeleteButton.vue
admin_ui/src/views/RowListing.vue

Hi Daniel
This is my attempt to make bulk delete rows on `currentPage` like in Django Admin. Suggestions and help is welcome. Bulk delete button is separate component but checkboxes is in `RowListing.vue` with logic on page change, table change etc.

making bulk delete option

---

admin_ui/src/components/DurationWidget.vue
admin_ui/src/components/InputField.vue
admin_ui/src/components/RowFilter.vue
admin_ui/src/utils.ts
admin_ui/src/views/RowListing.vue

@dantownsend Here is all changes made. You can easily see changes, test it and review it. Cheers.

Interval widget

---

admin_ui/src/components/InputField.vue
admin_ui/src/components/Pagination.vue
admin_ui/src/components/RowFilter.vue
admin_ui/src/components/RowSortModal.vue
admin_ui/src/views/RowListing.vue

Style improvements

---

admin_ui/src/components/ChangePageSize.vue
admin_ui/src/store.ts
admin_ui/src/views/RowListing.vue

Hi Daniel
Here is component for dynamically change page size in admin UI. Cheers.

component for dynamically change the page size

---

admin_ui/src/components/ChangePageSize.vue
admin_ui/src/components/Pagination.vue
admin_ui/src/components/RowFilter.vue
admin_ui/src/store.ts
admin_ui/src/views/RowListing.vue
piccolo_admin/endpoints.py

Building upon @sinisaos work https://github.com/piccolo-orm/piccolo_admin/pull/17
Moved the row number selector to the bottom of the page.
Cleaned up a few pre-existing issues.

Change page size

---

admin_ui/src/App.vue
admin_ui/src/components/AboutModal.vue
admin_ui/src/components/NavBar.vue
admin_ui/src/modules/aboutModal.ts
admin_ui/src/modules/meta.ts
admin_ui/src/store.ts
admin_ui/src/views/Home.vue
piccolo_admin/endpoints.py

- The site name can now be overridden (by default it's `Piccolo Admin`).
- Nav bar improvement - truncating the username if it's really long
- Some refactoring of Vuex state - created a module for storing metadata

Custom site name

---

docs/Makefile
docs/doc-requirements.txt
docs/serve_docs.py
docs/source/asgi/index.rst
docs/source/authentication/index.rst
docs/source/changes/index.rst
docs/source/conf.py
docs/source/index.rst
docs/source/installation/index.rst

@dantownsend My try to add Read the Docs. It's mostly from README.md and I'm adding a few things based on the GitHub issue you wrote the other day. I'm not an original English speaker, and there's probably a lot of mistakes, but that's just the start. Cheers.

adding documentation for admin

---

README.md
docs/Makefile
docs/doc-requirements.txt
docs/serve_docs.py
docs/source/asgi/index.rst
docs/source/authentication/index.rst
docs/source/changes/index.rst
docs/source/conf.py
docs/source/contributing/index.rst
docs/source/index.rst
docs/source/installation/index.rst

Building on top of https://github.com/piccolo-orm/piccolo_admin/pull/23 with minor tweaks.

Proper docs

---

admin_ui/src/App.vue
admin_ui/src/components/AddRowForm.vue
admin_ui/src/components/DropDownMenu.vue
admin_ui/src/components/InputField.vue
admin_ui/src/store.ts
admin_ui/src/views/AddRow.vue
admin_ui/src/views/BaseView.vue
admin_ui/src/views/Home.vue
admin_ui/src/views/Login.vue
admin_ui/src/views/RowListing.vue

Based on https://github.com/piccolo-orm/piccolo_admin/pull/25
We decided to fetch the meta from the API after a successful login.
Fixed some minor existing issues - such as unused axios imports.
Unfortunately the Vetur plugin for VSCode changed its formatter to prettier, and now there's a lot of churn when reformatting existing code.

Meta fixes

---

admin_ui/src/components/NavDropDownMenu.vue
admin_ui/src/views/Login.vue

Small path fix for auth. `/auth/login `and `/auth/logout` produce `404` error. It should be `./auth/login` and `./auth/logout/`.

small path fix for auth

---

CHANGES
admin_ui/package-lock.json
admin_ui/package.json
admin_ui/src/App.vue
admin_ui/src/components/BackButton.vue
admin_ui/src/components/RowFormSelect.vue
admin_ui/src/components/Tooltip.vue
admin_ui/src/main.ts
docs/source/help_text/index.rst
docs/source/index.rst
piccolo_admin/example.py
requirements.txt

First version of the UI for showing the help text tooltip.

Help text tooltips

---

.github/workflows/tests.yaml

Adding GitHub actions for running the unit tests. There aren't many unit tests currently, but I plan on adding more.

setup github actions

---

admin_ui/src/modules/meta.ts
admin_ui/src/views/Login.vue
extra/piccolo_admin
piccolo_admin/endpoints.py

Small changes to login page to include `site_name` in template.

Small changes to login page

---

admin_ui/package-lock.json
admin_ui/package.json
admin_ui/src/components/AddRowForm.vue
admin_ui/src/components/EditRowForm.vue
admin_ui/src/main.ts
piccolo_admin/example.py

There was a subtle bug where very large integer values were being shown incorrectly.
https://github.com/piccolo-orm/piccolo_admin/issues/55
This is due to a limitation of `JSON.loads`. To fix this, a custom `transformResponse` method was added to axios, which uses [json-bigint](https://www.npmjs.com/package/json-bigint).

fix big int accuracy

---

CHANGES

Small docs fix. I think you mean `choices` attribute set. If I'm wrong, just close this PR. Cheers.

small docs fix

---

admin_ui/src/main.less
admin_ui/src/vars.less

A subtle colour change for light mode - using a very light blue instead of grey.

changed light grey colour in light mode

---

docs/source/api_documentation/index.rst

Update api documentation for new Swagger interactive features. Cheers.

update API documentation

---

.flake8
.github/workflows/release.yaml
.github/workflows/tests.yaml
.gitignore
dev-requirements.txt
piccolo_admin/endpoints.py
piccolo_admin/example.py
piccolo_admin/example_data.py
piccolo_admin/piccolo_app.py
piccolo_admin/sandbox.py
pyproject.toml
scripts/README.md
scripts/lint.sh
scripts/release.sh
scripts/run-tests.sh
tests/piccolo_conf.py
tests/test-requirements.txt
tests/test_endpoints.py

Closes #72 
- Added the release.yaml, you need to get PyPI API token and set up `PYPI_TOKEN` secret for the project or organization in the Settings -> Secret.
- The results are not uploading to codecov yet. You need to set `CODECOV_TOKEN` secret for the project or organization
- Added isort (with black profile) and black to lint check to keep the codebase consistent.
If you could please enforce `Squash and merging` for all `piccolo` projects. I realized all my 20 commits in a PR were merged into master. That would pollute the history a bit. We can squash and merge PR with one commit into master, if you agree. If we decide to enforce it in the settings, we won't  forget to do it :)
I think that can be set for the whole organization.

add scripts folder

---

piccolo_admin/example.py
piccolo_admin/example_data.py

Added a JSON field to the example schema, so the UI for it can be easily tested / demoed.

Add a JSON field to the example schema

---

admin_ui/src/components/AddRowForm.vue

hide error message once save is successful

---

.github/workflows/tests.yaml
piccolo_admin/endpoints.py
piccolo_admin/example.py
pyproject.toml
requirements/test-requirements.txt
scripts/lint.sh
scripts/release.sh
scripts/run-tests.sh
tests/test_endpoints.py

increase coverage

---

piccolo_admin/endpoints.py
piccolo_admin/example.py
tests/test_endpoints.py

Form endpoints can now be async.

Async form endpoints

---

admin_ui/src/components/OperatorField.vue

fixing clearing filters bug

---

admin_ui/src/components/SidebarOverlay.vue

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/140

add z-index to sidebar

---

admin_ui/src/components/RowSortModal.vue
admin_ui/src/views/RowListing.vue
piccolo_admin/example.py
requirements/requirements.txt

Related to https://github.com/piccolo-orm/piccolo_admin/issues/81
This fixes the listing page when the table has a custom PK column name.

made the RowListing page work with custom PK name

---

.gitignore
CHANGES.rst
docs/source/asgi/index.rst
docs/source/conf.py
docs/source/help_text/index.rst
docs/source/index.rst
docs/source/rest_documentation/index.rst
piccolo_admin/endpoints.py
requirements/doc-requirements.txt

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/148

Update docs theme

---

docs/source/asgi/index.rst
docs/source/authentication/index.rst
docs/source/conf.py
docs/source/help_text/index.rst
docs/source/installation/index.rst
docs/source/table_config/index.rst
piccolo_admin/endpoints.py
piccolo_admin/example.py

* Added intersphinx.
* Refactored `create_admin` slightly so it looks better in autodoc

autodoc and intersphinx improvements

---

.github/workflows/release.yaml
.github/workflows/stale.yaml
.github/workflows/tests.yaml

Related to https://github.com/piccolo-orm/piccolo_admin/discussions/154
There will be a prompt after 30 days of inactivity on a PR, asking whether there are any blockers, or if it can be closed.

GitHub action for stale PRs

---

.github/workflows/stale.yaml

Related to https://github.com/piccolo-orm/piccolo_admin/discussions/154#discussioncomment-2412060

update cron schedule for stale PR check

---

.github/workflows/tests.yaml
piccolo_admin/endpoints.py
requirements/dev-requirements.txt
requirements/doc-requirements.txt
requirements/test-requirements.txt

Updated Sphinx and docs theme. Added more intersphinx links.

Improve docs

---

README.md

The README didn't mention a lot of the new features we've been adding.

add list of standout features to README

---

piccolo_admin/endpoints.py
tests/test_endpoints.py

media upload endpoints obey read_only option

---

admin_ui/src/components/InputField.vue
admin_ui/src/components/RowFormSelect.vue

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/207

fix custom forms

---

admin_ui/cypress/integration/CustomForm.spec.ts
admin_ui/cypress/integration/LoginAndLogout.spec.ts
admin_ui/cypress/integration/RowListingCrud.spec.ts
admin_ui/cypress/integration/RowListingFilter.spec.ts

update Cypress tests

---

docs/source/conf.py
docs/source/contributing/index.rst
requirements/doc-requirements.txt

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/204

Add link to GitHub in docs nav bar

---

piccolo_admin/example.py
piccolo_admin/example_data.py
piccolo_admin/translations/data.py

* Removing extraneous white space
* Making sure we have at least one unique column in `example.py`
* Fixing Mypy warnings
* Modernise some code in `example.py` (use `create_db_tables_sync` instead of a for loop)

Tidying up

---

piccolo_admin/example.py

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/217

Fix `admin_demo` script

---

admin_ui/src/components/AddRowForm.vue
admin_ui/src/components/BulkUpdateModal.vue
admin_ui/src/components/ChoiceSelect.vue
admin_ui/src/components/EditRowForm.vue
admin_ui/src/components/FormAdd.vue
admin_ui/src/components/InputField.vue
admin_ui/src/components/NewForm.vue
admin_ui/src/components/OperatorField.vue
admin_ui/src/components/RowFilter.vue
admin_ui/src/components/RowFormSearch.vue
admin_ui/src/components/RowFormSelect.vue
admin_ui/src/interfaces.ts

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/222

Allow camelcase column names

---

admin_ui/package-lock.json
admin_ui/package.json
admin_ui/public/css/flatpickr_dark.css
admin_ui/src/components/InputField.vue
e2e/test_playwright.py
piccolo_admin/example.py
piccolo_admin/example_data.py
requirements/test-requirements.txt
tests/test_endpoints.py

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/237

Fix datetime picker

---

admin_ui/src/App.vue

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/248

make HTML title match `site_name`

---

CHANGES.rst
piccolo_admin/endpoints.py

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/252

fix typo - should be passing a list of validators

---

.github/workflows/tests.yaml
setup.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/257

Add Python 3.11 support

---

admin_ui/src/components/ArrayWidget.vue
admin_ui/src/components/ChoiceSelect.vue
admin_ui/src/components/InputField.vue
e2e/test_playwright.py
piccolo_admin/example.py
requirements/requirements.txt

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/161

support choices for array columns

---

admin_ui/src/components/AddRowForm.vue
admin_ui/src/components/EditRowForm.vue

scroll to top after form error

---

piccolo_admin/endpoints.py

Fix for [issue](https://github.com/piccolo-orm/piccolo/issues/749)

fix for new version of FastAPI

---

admin_ui/src/components/AddRowForm.vue
admin_ui/src/components/EditRowForm.vue
admin_ui/src/components/InputField.vue
admin_ui/src/utils.ts
admin_ui/src/views/RowListing.vue
piccolo_admin/example.py
tests/test_endpoints.py

Related to https://github.com/piccolo-orm/piccolo_admin/issues/290

Nullable number fields

---

admin_ui/src/utils.ts
piccolo_admin/example.py

Related to https://github.com/piccolo-orm/piccolo_admin/issues/290

UUID nullable columns

---

e2e/pages.py
e2e/test_null_columns.py

The fixes from https://github.com/piccolo-orm/piccolo_admin/pull/283/
Need this merged in as Playwright tests are failing, and makes the other PR smaller.

playwright fixes

---

piccolo_admin/endpoints.py
piccolo_admin/example.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/301

use generics for `FormConfig`

---

admin_ui/src/components/ArrayWidget.vue

Small fix related to enable item list display in custom forms. Related to #298

enable list items in custom forms

---

admin_ui/src/utils.ts
e2e/test_null_columns.py
piccolo_admin/example.py

make nullable email work

---

admin_ui/src/components/InputField.vue
admin_ui/src/utils.ts
e2e/test_null_columns.py
piccolo_admin/example.py
requirements/test-requirements.txt

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/314

Fix nullable date fields

---

requirements/requirements.txt

Related to [this issue](https://github.com/piccolo-orm/piccolo_admin/issues/313)

pin FastAPI and Pydantic 1 version

---

admin_ui/src/components/InputField.vue
piccolo_admin/example.py
piccolo_admin/example_data.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/318

Improve UI for JSON fields

---

admin_ui/src/utils.ts
e2e/test_null_columns.py
piccolo_admin/example.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/331

treat empty strings on nullable varchar / text as null

---

e2e/test_add_row.py
e2e/test_date_time_columns.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/341

Make Playwright tests more reliable

---

admin_ui/src/components/NavBar.vue
admin_ui/src/components/SidebarNav.vue
admin_ui/src/components/SidebarOverlay.vue
admin_ui/src/views/BaseView.vue

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/342

342 Improve sidebar styling

---

admin_ui/package-lock.json
admin_ui/package.json
requirements/dev-requirements.txt

Fixes https://github.com/piccolo-orm/piccolo_admin/security/dependabot/7
Fixes https://github.com/piccolo-orm/piccolo_admin/security/dependabot/8

fix dependabot alerts

---

admin_ui/src/components/BulkUpdateModal.vue
admin_ui/src/components/FilterForm.vue
admin_ui/src/components/InputField.vue
admin_ui/src/components/MatchField.vue
admin_ui/src/components/NewForm.vue
admin_ui/src/components/RowFilter.vue
admin_ui/src/components/RowForm.vue
e2e/pages.py
e2e/test_match.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/349

349 Support `match` param

---

admin_ui/src/components/FilterForm.vue

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/356

356 Fix regression with JSON filters being visible

---

admin_ui/src/components/ArrayWidget.vue
admin_ui/src/views/RowListing.vue
e2e/pages.py
e2e/test_choices.py
piccolo_admin/example.py
tests/test_endpoints.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/363

Fix array choices

---

admin_ui/src/components/ArrayWidget.vue

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/367

367 Fix filtering of array columns when they have choices

---

e2e/pages.py
e2e/test_array_columns.py
e2e/test_choices.py
e2e/test_constraints.py
piccolo_admin/example.py
requirements/test-requirements.txt
scripts/dev-server.sh
tests/test_endpoints.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/373

373 Add E2E tests for arrays

---

admin_ui/src/views/RowListing.vue

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/375

375 Translation Issue with Bulk Update Button

---

admin_ui/src/components/ArrayWidget.vue
piccolo_admin/endpoints.py

fix bug in array widget

---

admin_ui/src/components/FormAdd.vue
admin_ui/src/utils.ts

Just a small change to reduce code repetition.

use `convertFormValue` in custom forms

---

admin_ui/src/components/InputField.vue
admin_ui/src/interfaces.ts
e2e/pages.py
e2e/test_array_columns.py
piccolo_admin/example.py
requirements/requirements.txt

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/393

393 Improve the array widgets for time / date / timestamp

---

admin_ui/src/components/NavDropDownMenu.vue

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/409

409 Make `MFA Setup` URL relative

---

docs/source/mfa/index.rst

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/408

408 Add in depth documentation about MFA

---

docs/source/custom_forms/examples/app.py
docs/source/custom_forms/index.rst
piccolo_admin/example/forms/__init__.py
piccolo_admin/example/forms/calculator.py
piccolo_admin/sandbox.py
tests/test_endpoints.py

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/420

420 Add some forms to the sandbox

---

MANIFEST.in

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/422

422 Add missing JPEG file for example form

---

.github/workflows/playwright.yaml

This was causing the Playwright tests to fail.

Use newer version of `actions/upload-artifact`
