piccolo-orm/piccolo_admin

admin_ui/src/components/NavBar.vue
admin_ui/src/store.ts
piccolo_admin/endpoints.py

Hi Daniel
here is my attempt to add ability to change site name instead of the default `Piccolo Admin` in `create_admin`. Cheers.

ability to change site name instead of default Piccolo

---

admin_ui/src/modules/meta.ts
admin_ui/src/views/Home.vue

@dantownsend Minor fixes for a custom site name because metadata doesn't display properly until the page refreshes. You can see that in [demo](https://demo1.piccolo-orm.com/#/login?nextURL=%2F), version in the modal is `Unknown` until you refresh the page. With these changes, everything should be fine with the first page view (at least that's the case with me), but you check it out. Cheers.

minor meta fix

---

piccolo_admin/example.py
piccolo_admin/sandbox.py
requirements.txt

`example.py` can now run using Postgres, as well as SQLite. This is very useful for testing if new column types work with the admin.
The CLI for `example.py` and `sandbox.py` were also converted to use targ, rather than `sys.argv`.

updated example.py to use targ and to support postgres

---

admin_ui/src/components/AddRowForm.vue

Small fix when column name contains underscore in Schema definition. 
```
class Task(Table):
"""
An Task table.
"""
name = Varchar()
description = Text()
completed = Boolean(default=False)
task_user = ForeignKey(references=BaseUser) # <- like this underscore 
```
With this change column content will display correctly in piccolo admin after creation.

small underscore fix

---

admin_ui/src/components/RowFilter.vue

Small fix for clear filters in `RowFilter.vue`. Duration widget are not properly cleaned. Now all fields is properly cleaned.

fix clear filters for duration widget

---

docs/source/contributing/index.rst
piccolo_admin/example.py
piccolo_admin/example_data.py
setup.py

Added an option to the `example.py` CLI, which will populate lots of extra data in the database.
```
python -m piccolo_admin.example --inflate=10000
```
This is really useful when testing the performance of the admin with large data sets.

added `inflate` option to example.py, for generating lots of dummy data

---

admin_ui/src/components/Tooltip.vue
admin_ui/src/views/RowListing.vue
docs/source/help_text/index.rst
piccolo_admin/example.py
requirements.txt

If a `Table` has the `help_text` attribute, show it as a tooltip in the UI.

add tooltip for table help text

---

piccolo_admin/endpoints.py
requirements.txt

The Swagger docs in the Piccolo admin should now work with POST requests (Piccolo's CSRF middleware used to block it).

Add custom Swagger UI from piccolo_api

---

piccolo_admin/endpoints.py

This was my mistake - the form will fail if the description is None.

fix bug with description not being optional

---

admin_ui/src/components/ChoiceSelect.vue

There was a minor bug with filters when the column had choices.
It was defaulting to 'Null' rather than 'All'.

fix choice filter

---

piccolo_admin/endpoints.py

The `create_admin` docstring was missing a param for `forms`, and the type annotation was incorrect. Also, adding missing backticks.

improve the `create_admin` docstring

---

piccolo_admin/endpoints.py

We're importing `BaseUser` from two places - just a minor tidy up.

remove duplicate pydantic import

---

admin_ui/src/main.less

I only realised today that `font-family` in CSS doesn't automatically apply to `button` or `textarea` elements.
This PR adds this, and increases the font size slightly.

fix font family

---

admin_ui/src/components/NewForm.vue
piccolo_admin/endpoints.py
piccolo_admin/example.py
tests/test_endpoints.py

Related to https://github.com/piccolo-orm/piccolo_admin/issues/134
We can make static default values work for forms with very little work, so makes sense to release this.
It's a bit more work to make dynamic defaults work - not impossible, but we'll need a new endpoint.
So now, if your Pydantic model is this:
```python
class BusinessEmailModel(BaseModel):
email: str
title: str = "Enquiry"
content: str
```
Then it renders this:

show defaults in custom forms

---

admin_ui/src/components/DropDownMenu.vue
admin_ui/src/components/Modal.vue

Small `z-index` fix for modal and dropdown menu.
Before:
After:

fixing z-index for modal and dropdown menu

---

docs/source/asgi/examples/fastapi/app.py
docs/source/asgi/examples/fastapi/movies/endpoints.py
docs/source/asgi/examples/fastapi/movies/tables.py
docs/source/asgi/examples/starlette/app.py
docs/source/asgi/examples/starlette/movies/endpoints.py
docs/source/asgi/examples/starlette/movies/tables.py
docs/source/asgi/index.rst
docs/source/custom_forms/examples/app.py
docs/source/custom_forms/examples/home/tables.py
docs/source/custom_forms/index.rst
docs/source/index.rst
piccolo_admin/endpoints.py

Rather than having large code snippets written inline within the docs, it's better to embed actual Python files because they can be tested and linted.

using literal includes for large code snippets

---

piccolo_admin/endpoints.py

Print warning in AdminRouter#__init__ for Piccolo columns using `secret` and `required` column kwargs.
See #162 for summary of issue.
I'd initially attempted to write a test to verify this behavior but there wasn't a clear path towards doing so. (I was able to use the test suite to drive out my implementation, though.)
I'd also prefer to use a proper logger instance/method instead of `print` but there aren't any others in use in this project and I wasn't sure if introducing one would be welcomed.

Warn when Piccolo columns use secret and required kwargs

---

docs/source/table_config/index.rst
piccolo_admin/endpoints.py
tests/test_endpoints.py

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/179
Allows users to run custom logic when a row is creating / deleted / modified.

exposing `PiccoloCRUD`'s hooks

---

piccolo_admin/endpoints.py
tests/test_endpoints.py

Fix for issue with `exclude_visible_columns` for `TableConfig`.
Right now `exclude_visible_columns` parameter is not working if the primary key column is not in the list of excluded columns.  This PR introduces a possible quick fix for that problem.

Fixed exclude_visible_columns for TableConfig

---

piccolo_admin/endpoints.py

Fixes https://github.com/piccolo-orm/piccolo_admin/issues/262

allow `BaseUser` subclass to be used, which uses a `UUID` primary key

---

admin_ui/src/components/InputField.vue
admin_ui/src/utils.ts
e2e/test_null_columns.py
piccolo_admin/example.py

If you have a nullable JSON / JSONB column in Piccolo Admin, when you try saving it you would get a validation error.
For now, I'm assuming that if a JSON column is nullable, and the value is empty, then treat it as NULL instead of an empty string, as that's probably the intention.

improve nullable JSON fields in Piccolo Admin

---

.github/workflows/playwright.yaml
.github/workflows/release.yaml
piccolo_admin/endpoints.py

By default, we're going to rate limit more aggressively - the user can always override this behaviour if they choose via the `rate_limit_provider` argument of `create_piccolo_admin`.

More aggressive rate limiting

---

admin_ui/src/components/FilterForm.vue
admin_ui/src/views/RowListing.vue
e2e/conftest.py
e2e/pages.py
e2e/test_null_columns.py
piccolo_admin/example.py
requirements/test-requirements.txt

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/339
Remaining tasks:

339: Fix nullable boolean columns in filter sidebar

---

admin_ui/src/components/OperatorField.vue
e2e/pages.py
e2e/test_operator.py
requirements/requirements.txt

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/351

351 add `ne` operator

---

README.md

The original example is missing the imports for `Mount` and `Hello`. I propose using the [provided example for the documentation](https://github.com/piccolo-orm/piccolo_admin/blob/master/docs/source/asgi/examples/starlette/app.py) to replace it.

Enhance ASGI Example in README.md

---

piccolo_admin/translations/data.py

As mentioned in this [PR](https://github.com/piccolo-orm/piccolo_admin/pull/205), some words may not directly translate from English to either `zh-CN` or `zh-TW`, but we've made our best effort to provide accurate translations. :smile:

Improve `zh-TW` translation

---

admin_ui/src/components/BulkUpdateModal.vue
admin_ui/src/interfaces.ts
e2e/test_codegen.py
requirements/requirements.txt

Related to this [issue](https://github.com/piccolo-orm/piccolo_api/issues/273). This PR will disable unique columns in bulk update. This change will work when a new version of Piccolo ORM is released. Playwright tests will also pass after new Piccolo ORM release, because for now `BulkUpdate` dropdown is empty

disable unique column in BulkUpdate dropdown

---

.github/workflows/tests.yaml

Out CI is currently blocked, because our coverage results can't be uploaded to codecov.io.
Try updating the Codecov GitHub Action to see if that helps.

Update Codecov GitHub Action

---

admin_ui/src/components/AddRowForm.vue
admin_ui/src/components/EditRowForm.vue
admin_ui/src/main.less

Resolves https://github.com/piccolo-orm/piccolo_admin/issues/396

396 Disabling the save button after click

---

admin_ui/src/components/FormNav.vue
admin_ui/src/components/SidebarGroup.vue
admin_ui/src/components/TableNav.vue
admin_ui/src/store.ts
docs/source/custom_forms/examples/app.py
piccolo_admin/endpoints.py
piccolo_admin/example/forms/csv.py
piccolo_admin/example/forms/email.py
piccolo_admin/example/forms/image.py
tests/test_endpoints.py

419 Group forms in the sidebar

---

docs/source/mfa/index.rst

Fixing a small mistake around encryption key generation in docs. `XChaCha20Provider.generate_key()` raise `AttributeError: type object 'XChaCha20Provider' has no attribute 'generate_key'` (because `generate_key` is [Fernet method](https://github.com/piccolo-orm/piccolo_api/blob/bc7eefa9d63b018cf45853798acbfd0be0978754/piccolo_api/encryption/providers.py#L112C16-L112C37)). I think it should be https://github.com/piccolo-orm/piccolo_api/blob/bc7eefa9d63b018cf45853798acbfd0be0978754/piccolo_api/encryption/providers.py#L179

fix wrong method in docs

---

.github/workflows/playwright.yaml
piccolo_admin/endpoints.py
requirements/test-requirements.txt

Pulling it out of this other PR, which was getting too large: https://github.com/piccolo-orm/piccolo_admin/pull/432
Playwright doesn't currently work in our CI, because of some missing dependencies in the latests Ubuntu LTS.
We also need to remove the version pin for FastAPI, because of some changes with Starlette's `TestClient`.

Fix Playwright and Linters in CI

---

admin_ui/src/App.vue
admin_ui/src/components/AddRowForm.vue
admin_ui/src/components/CSVModal.vue
admin_ui/src/components/EditRowForm.vue
admin_ui/src/components/FormAdd.vue
admin_ui/src/components/InputField.vue
admin_ui/src/components/KeySearchModal.vue
admin_ui/src/components/OrderByModal.vue
admin_ui/src/components/Pagination.vue
admin_ui/src/components/RowFilter.vue
admin_ui/src/components/RowForm.vue
admin_ui/src/components/TimeWidget.vue
admin_ui/src/components/TimestampWidget.vue
admin_ui/src/components/TimestamptzWidget.vue
admin_ui/src/components/Tooltip.vue
admin_ui/src/views/Login.vue
admin_ui/src/views/RowListing.vue

When we upgraded to the latest JS dependencies, ESLint will auto fix some linter errors - simple stuff like using `let` instead of `const`.

ESLint fixes

---

e2e/pages.py
piccolo_admin/endpoints.py
piccolo_admin/example/app.py
piccolo_admin/example/data.py
piccolo_admin/example/forms/nullable.py
piccolo_admin/example/tables.py
piccolo_admin/translations/data.py
piccolo_admin/translations/models.py
setup.py

Improved type hints for Python 3.9 and later. This can be done in other Piccolo repositories as well. [See comment](https://github.com/piccolo-orm/piccolo/issues/1208)

type hint update for Python 3.9 and later
